//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSuperHeroes.Z_Capa3_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marvel
    {
        public long Id { get; set; }
        public long IdSuperHumanos { get; set; }
        public bool Vengadores { get; set; }
    
        public virtual SuperHumanos SuperHumanos { get; set; }
    }
}
