//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSuperHeroes.Z_Capa3_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanitario
    {
        public long Id { get; set; }
        public long IdProfesionesHeroicas { get; set; }
        public bool Curar { get; set; }
    
        public virtual ProfesionesHeroicas ProfesionesHeroicas { get; set; }
        public virtual SuperHeroe SuperHeroes { get; set; }
    }
}
