//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSuperHeroes.Z_Capa3_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperHumanos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuperHumanos()
        {
            this.DC = new HashSet<DC>();
            this.Marvel = new HashSet<Marvel>();
        }
    
        public long Id { get; set; }
        public long IdSuperHeroe { get; set; }
        public bool Volar { get; set; }
        public bool SuperFuerza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC> DC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marvel> Marvel { get; set; }
        public virtual SuperHeroe SuperHeroe { get; set; }
    }
}
